# Azure
azure_env: CHANGEME
azure_subscription_id: CHANGEME
azure_tenant_id: CHANGEME
azure_client_id: CHANGEME
azure_client_secret: CHANGEME
azure_storage_account_name: CHANGEME
azure_storage_account_key: CHANGEME
azure_storage_container_tfstate: CHANGEME
azure_storage_container_cpi: CHANGEME

# PCF
pcf_env_name: CHANGEME
pcf_short_env_name: CHANGEME
pcf_location: CHANGEME
pcf_opsman_image_uri: CHANGEME
pcf_opsman_admin_username: CHANGEME
pcf_opsman_admin_password: CHANGEME
pcf_dns_suffix: CHANGEME
srt_major_minor_version: CHANGEME
pcf_srt_mysql_monitor_recipient_email: CHANGEME

# CPI
cpi_source_branch: CHANGEME

# Pivotal network
pivnet_token: CHANGEME