---

resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: terraforming-azure
  type: git
  source:
    uri: https://github.com/pivotal-cf/terraforming-azure.git
    branch: master

- name: azure-pcf-pipeline
  type: git
  source:
    uri: https://github.com/walk1ng/azure-pcf-pipeline.git
    branch: master

- name: terraform-tfstate
  type: azure-blobstore
  source:
    storage_account_name: ((azure_storage_account_name))
    storage_account_key: ((azure_storage_account_key))
    container: ((azure_storage_container_tfstate))
    versioned_file: terraform.tfstate

- name: bosh-cpi-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-azure-cpi-release.git
    branch: ((cpi_source_branch))
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml

- name: bosh-cpi-validate-release
  type: azure-blobstore
  source:
    storage_account_name: ((azure_storage_account_name))
    storage_account_key: ((azure_storage_account_key))
    container: ((azure_storage_container_cpi))
    versioned_file: bosh-azure-cpi

- name: pivnet-small-footprint-pas
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((srt_major_minor_version))

jobs:
- name: create-iaas-infra
  public: true
  ensure:
    put: terraform-tfstate
    params:
      file: terraform-tfstate/terraform.tfstate
  plan:
  - aggregate:
    - get: terraforming-azure
    - get: azure-pcf-pipeline
  - task: create-infrastructure
    file: azure-pcf-pipeline/tasks/terraform-infrastructure/task.yml
    params:
      AZURE_SUBSCRIPTION_ID: ((azure_subscription_id))
      AZURE_TENANT_ID: ((azure_tenant_id))
      AZURE_CLIENT_ID: ((azure_client_id))
      AZURE_CLIENT_SECRET: ((azure_client_secret))
      PCF_ENV_NAME: ((pcf_env_name))
      PCF_SHORT_ENV_NAME: ((pcf_short_env_name))
      PCF_LOCATION: ((pcf_location))
      PCF_OPSMAN_IMAGE_URI: ((pcf_opsman_image_uri))
      PCF_DNS_SUFFIX: ((pcf_dns_suffix))

- name: config-opsman-auth
  public: true
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
      - get: terraform-tfstate
        passed: [create-iaas-infra]
        trigger: true
    - task: config-opsman
      file: azure-pcf-pipeline/tasks/config-opsman/task.yml
      params:
        PCF_OPSMAN_ADMIN: ((pcf_opsman_admin_username))
        PCF_OPSMAN_ADMIN_PASSWORD: ((pcf_opsman_admin_password))
  
- name: config-director
  public: true
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
      - get: terraform-tfstate
        passed: [config-opsman-auth]
        trigger: true
    - task: config-director
      file: azure-pcf-pipeline/tasks/config-director/task.yml
      params:
        PCF_OPSMAN_ADMIN: ((pcf_opsman_admin_username))
        PCF_OPSMAN_ADMIN_PASSWORD: ((pcf_opsman_admin_password))
        AZURE_ENV: ((azure_env))
        AZURE_SUBSCRIPTION_ID: ((azure_subscription_id))
        AZURE_TENANT_ID: ((azure_tenant_id))
        AZURE_CLIENT_ID: ((azure_client_id))
        AZURE_CLIENT_SECRET: ((azure_client_secret))

- name: build-bosh-azure-cpi
  public: true
  ensure:
    put: bosh-cpi-validate-release
    params:
      file: builds/bosh-azure-cpi-((cpi_source_branch)).tgz
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
        passed: [config-director]
        trigger: true
      - get: bosh-cpi-src
    - task: build-cpi
      file: azure-pcf-pipeline/tasks/build-cpi/task.yml
      params:
        CPI_SOURCE_BRANCH: ((cpi_source_branch))

- name: config-bosh-azure-cpi
  public: true
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
      - get: terraform-tfstate
      - get: bosh-cpi-validate-release
        passed: [build-bosh-azure-cpi]
        trigger: true
    - task: config-cpi
      file: azure-pcf-pipeline/tasks/config-cpi/task.yml

- name: deploy-director
  public: true
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
      - get: terraform-tfstate
        passed: [config-bosh-azure-cpi]
        trigger: true
    - task: deploy-director
      file: azure-pcf-pipeline/tasks/deploy-director/task.yml
      params:
        PCF_OPSMAN_ADMIN: ((pcf_opsman_admin_username))
        PCF_OPSMAN_ADMIN_PASSWORD: ((pcf_opsman_admin_password))

- name: upload-srt
  public: true
  plan:
    - aggregate:
      - get: azure-pcf-pipeline
      - get: terraform-tfstate
        passed: [deploy-director]
        trigger: true
      - get: pivnet-product
        resource: pivnet-small-footprint-pas
        params:
          globs: ["srt-*.pivotal"]
    - task: upload-srt-tile
      file: azure-pcf-pipeline/tasks/upload-product-and-stemcell/task.yml
      params:
        OPSMAN_CLIENT_ID: ""
        OPSMAN_CLIENT_SECRET: ""
        PCF_OPSMAN_ADMIN: ((pcf_opsman_admin_username))
        PCF_OPSMAN_ADMIN_PASSWORD: ((pcf_opsman_admin_password))
        PIVNET_API_TOKEN: ((pivnet_token))
        IAAS: "azure"
    - task: stage-srt-tile
      file: azure-pcf-pipeline/tasks/stage-product/task.yml
      params:
        OPSMAN_CLIENT_ID: ""
        OPSMAN_CLIENT_SECRET: ""
        PCF_OPSMAN_ADMIN: ((pcf_opsman_admin_username))
        PCF_OPSMAN_ADMIN_PASSWORD: ((pcf_opsman_admin_password))
        PRODUCT_NAME: "cf"
        PRODUCT_VERSION: ((srt_major_minor_version))