---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
  - name: resource-azure-pcf-pipeline
  - name: resource-bosh-cpi-src

outputs:
  - name: builds

run:
  path: resource-azure-pcf-pipeline/tasks/build-cpi/task.sh

params:
  CPI_SOURCE_BRANCH: