---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: terraform-tfstate
  - name: azure-pcf-pipeline

run:
  path: azure-pcf-pipeline/tasks/deploy-director/task.sh

params:
  PCF_OPSMAN_ADMIN:
  PCF_OPSMAN_ADMIN_PASSWORD:
