---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: terraform-tfstate
  - name: azure-pcf-pipeline

run:
  path: azure-pcf-pipeline/tasks/config-director/task.sh

params:
  PCF_OPSMAN_ADMIN:
  PCF_OPSMAN_ADMIN_PASSWORD:
  AZURE_ENV:
  AZURE_SUBSCRIPTION_ID:
  AZURE_TENANT_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
