---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: resource-terraform-tfstate
  - name: resource-azure-pcf-pipeline
  - name: resource-pivnet-product

run:
  path: resource-azure-pcf-pipeline/tasks/upload-product-and-stemcell/task.sh

params:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  PCF_OPSMAN_ADMIN:
  PCF_OPSMAN_ADMIN_PASSWORD:
  PIVNET_API_TOKEN:
  IAAS: