---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: terraform-tfstate
  - name: azure-pcf-pipeline
  - name: bosh-cpi-validate-release

run:
  path: azure-pcf-pipeline/tasks/config-cpi/task.sh
