---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: resource-terraform-tfstate
  - name: resource-azure-pcf-pipeline
  - name: resource-bosh-cpi-validate-release

run:
  path: resource-azure-pcf-pipeline/tasks/config-cpi/task.sh
